---
_process:
    - mode: gate
      when: "{{ protocol_key != 'static static' }}"
static:
    _process:
        - mode: block
          regexp: "(?P<block>ip route (?P<key>\\d+\\S+ \\d+\\S+).*)"
          from: "{{ bookmarks['network-instances'][0] }}"
          when: "{{ network_instance_key == 'global' }}"
          flat: true
          post_process_filter: "addrmask_to_cidr"
        - mode: block
          regexp: "(?P<block>ip route vrf {{ network_instance_key }} (?P<key>\\d+\\S+ \\d+\\S+).*)"
          from: "{{ bookmarks['network-instances'][0] }}"
          when: "{{ network_instance_key != 'global' }}"
          flat: true
          post_process_filter: "addrmask_to_cidr"
        - mode: block
          regexp: "(?P<block>ipv6 route (?P<key>[0-9a-f:]+\\/\\d+).*)"
          from: "{{ bookmarks['network-instances'][0] }}"
          when: "{{ network_instance_key == 'global' }}"
          flat: true
        - mode: block
          regexp: "(?P<block>ipv6 route vrf {{ network_instance_key }} (?P<key>[0-9a-f:]+\\/\\d+).*)"
          from: "{{ bookmarks['network-instances'][0] }}"
          when: "{{ network_instance_key != 'global' }}"
          flat: true
          post_process_filter: "addrmask_to_cidr"
    config:
        _process: unnecessary
        prefix:
            _process:
                - mode: value
                  value: "{{ static_key }}"
        set-tag:
            _process: not_implemented
    next-hops:
        _process: unnecessary
        next-hop:
            _process:
                - mode: block
                  regexp: "(?P<block>ip route (vrf {{ network_instance_key }} )*\\d+\\S+ \\d+\\S+ (?P<key>\\d+.\\d+.\\d+.\\d+).*)"
                  from: "{{ bookmarks['static'][static_key] }}"
                - mode: block
                  regexp: "(?P<block>ipv6 route (vrf {{ network_instance_key }} )*{{ static_key }} (?P<key>[0-9a-f:]+).*)"
                  from: "{{ bookmarks['static'][static_key] }}"
            config:
                _process: unnecessary
                index:
                    _process: not_implemented
                metric:
                    _process:
                        - mode: search
                          regexp: "{{ next_hop_key }} (?P<value>\\d+)"
                          from: "{{ bookmarks.parent }}"
                next-hop:
                    _process:
                        - mode: value
                          value: "{{ next_hop_key }}"
                recurse:
                    _process: not_implemented
            index:
                _process: not_implemented
            interface-ref:
                _process: not_implemented
                config:
                    _process: not_implemented
                    interface:
                        _process: not_implemented
                    subinterface:
                        _process: not_implemented
                state:
                    _process: not_implemented
            state:
                _process: not_implemented
    prefix:
        _process: not_implemented
    state:
        _process: not_implemented

