---
_process:
    - mode: gate
      when: "{{ protocol_key != 'static static' }}"
static:
    _process:
        - mode: block
          regexp: "(?P<block>ip route (?P<key>\\d+\\S+ \\d+\\S+).*)"
          from: "{{ bookmarks['network-instances'][0] }}"
          when: "{{ network_instance_key == 'global' }}"
          flat: true
          post_process_filter: "addrmask_to_cidr"
        - mode: block
          regexp: "(?P<block>ip route vrf {{ network_instance_key }} (?P<key>\\d+\\S+ \\d+\\S+).*)"
          from: "{{ bookmarks['network-instances'][0] }}"
          when: "{{ network_instance_key != 'global' }}"
          flat: true
          post_process_filter: "addrmask_to_cidr"
        - mode: block
          regexp: "(?P<block>ipv6 route (?P<key>[0-9a-f:]+\\/\\d+).*)"
          from: "{{ bookmarks['network-instances'][0] }}"
          when: "{{ network_instance_key == 'global' }}"
          flat: true
        - mode: block
          regexp: "(?P<block>ipv6 route vrf {{ network_instance_key }} (?P<key>[0-9a-f:]+\\/\\d+).*)"
          from: "{{ bookmarks['network-instances'][0] }}"
          when: "{{ network_instance_key != 'global' }}"
          flat: true
    config:
        _process: unnecessary
        prefix:
            _process:
                - mode: value
                  value: "{{ static_key }}"
        set-tag:
            _process: not_implemented
    next-hops:
        _process: unnecessary
        next-hop:
            _process:
                - mode: block
                  regexp: "(?P<block>ip route (vrf {{ network_instance_key }} )*\\d+\\S+ \\d+\\S+ (?P<key>(?:(?P<interface_ref>[a-z]\\S*) ?)?(?P<next_hop>\\d+.\\d+.\\d+.\\d+)?).*)"
                  from: "{{ bookmarks['static'][static_key] }}"
                  post_process_filter: "{{ key|trim }}"
                - mode: block
                  regexp: "(?P<block>ipv6 route (vrf {{ network_instance_key }} )*{{ static_key }} (?P<key>(?:(?P<interface_ref>[a-z]\\S*) ?)?(?P<next_hop>[0-9a-f:]+:[0-9a-f:]+)?).*)"
                  from: "{{ bookmarks['static'][static_key] }}"
                  post_process_filter: "{{ key|trim }}"
            config:
                _process: unnecessary
                index:
                    _process: unnecessary
                metric:
                    _process:
                        - mode: search
                          regexp: "{{ next_hop_key }} (?P<value>\\d+)"
                          from: "{{ bookmarks.parent }}"
                next-hop:
                    _process:
                        - mode: value
                          value: "DROP"
                          when: "{{ extra_vars.interface_ref == 'Null0' }}"
                        - mode: value
                          value: "{{ extra_vars.next_hop }}"
                          when: "{{ extra_vars.next_hop is not none }}"
                recurse:
                    _process: not_implemented
            index:
                _process: unnecessary
            interface-ref:
                _process: unnecessary
                config:
                    _process:
                        - mode: gate
                          when: "{{ extra_vars.interface_ref is none }}"
                    interface:
                        _process:
                            - mode: search
                              regexp: "^(?P<value>[^\\.]+).*"
                              from: "{{ extra_vars.interface_ref }}"
                    subinterface:
                        _process:
                            - mode: search
                              regexp: ".+\\.(?P<value>.+)"
                              from: "{{ extra_vars.interface_ref }}"
                state:
                    _process: not_implemented
            state:
                _process: not_implemented
    prefix:
        _process: unnecessary
    state:
        _process: not_implemented

